name: E2E Tests

on:
  push:
    branches:
      - main
      - v2

  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/ci-setup

      - name: Set up supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest
          run: supabase start

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run e2e tests
        run: pnpm run test:e2e
